services:
  continuwuity:
    image: forgejo.ellis.link/continuwuation/continuwuity:latest
    container_name: continuwuity
    restart: unless-stopped
    volumes:
      - ./continuwuity.toml:/var/lib/continuwuity/continuwuity.toml:ro
      - ./data:/var/lib/continuwuity
    environment:
      CONDUWUIT_CONFIG: "/var/lib/continuwuity/continuwuity.toml"
      CONTINUWUITY_CONFIG: "/var/lib/continuwuity/continuwuity.toml"
    networks:
      - reverse_proxy_network


networks:
  reverse_proxy_network:
      external: true
